name: Auto Commit
on:
  schedule:
    - cron: 0 10 * * *
  workflow_dispatch:
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run commit script
        run: |
          git remote set-url origin https://leodahal4:${MY_TOKEN}@github.com/leodahal4/autocommit-fun.git
          git config --global user.email "leodahal4@gmail.com"
          git config --global user.name "Mou Sam Dahal"
          num_commits=$(($RANDOM % 10 + 1))
          for ((i=1; i<=num_commits; i++)); do
             git commit --allow-empty -m "Oops commit $i - Random: $(date +%s)"
          done
          git push origin main